services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_PORT: ${DB_PORT}
    secrets:
      - db_password
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - msm-net

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--port ${REDIS_PORT}
    networks:
      - msm-net

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      BACKUP_STORAGE_PATH: ${BACKUP_STORAGE_PATH}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      PAYMENT_RETURN_URL: ${PAYMENT_RETURN_URL}
    secrets:
      - db_password
      - jwt_secret_key
      - backup_encryption_key
      - yookassa_secret_key
    volumes:
      - ./src/api:/app/src/api
      - ./src/common/services:/app/src/common/services
      - backup_storage_data:${BACKUP_STORAGE_PATH}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - msm-net

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    secrets:
      - db_password
    volumes:
      - ./alembic:/app/alembic
    depends_on:
      - postgres
    networks:
      - msm-net

volumes:
  postgres-data:
    name: postgres-data

  backup_storage_data:
    name: backup_storage_data

networks:
  msm-net:
    driver: bridge

secrets:
  backup_encryption_key:
    file: ./secrets/backup_encryption_key.txt

  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt

  db_password:
    file: ./secrets/db_password.txt

  yookassa_secret_key:
    file: ./secrets/yookassa_secret_key.txt
