FROM python:3.14

COPY ./src/api /app/src/api
COPY ./src/common/database /app/src/common/database
COPY ./src/common/repositories /app/src/common/repositories
COPY ./src/common/core /app/src/common/core
COPY ./poetry.lock ./pyproject.toml /app 

WORKDIR /app

RUN pip install poetry
RUN poetry install --only main --no-root

CMD ["poetry", "run", "python3", "-m", "src.api"]
