FROM python:3.14

COPY ./alembic /app/alembic
COPY ./src/common/database /app/src/common/database
COPY ./src/common/core /app/src/common/core
COPY ./poetry.lock ./pyproject.toml ./alembic.ini /app 

WORKDIR /app

RUN pip install poetry
RUN poetry install --only main --no-root

CMD ["poetry", "run", "alembic", "upgrade", "head"]