"""remove the daemon_keys table and add a key_hash column to the servers table

Revision ID: 27e313a91020
Revises: 781218c471cf
Create Date: 2026-08-12 13:38:10.703711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e313a91020'
down_revision: Union[str, Sequence[str], None] = '781218c471cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daemon_keys')
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'external_payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('payments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('server_users', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('server_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('server_users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('server_users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('servers', sa.Column('daemon_key_hash', sa.String(), nullable=False))
    op.alter_column('servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('servers', 'daemon_key_hash')
    op.alter_column('server_users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('server_users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('server_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('server_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('server_users', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'external_payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('daemon_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('daemon_keys_server_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daemon_keys_pkey'))
    )
    # ### end Alembic commands ###
