"""add uq_idx_active_subscription_per_user index to the subscriptions table

Revision ID: 29afc3ee2589
Revises: a7af429f2b9a
Create Date: 2026-08-27 14:15:59.841404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29afc3ee2589'
down_revision: Union[str, Sequence[str], None] = 'a7af429f2b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_idx_active_subscription_per_user', 
        'subscriptions', 
        ['user_id'], 
        unique=True, 
        postgresql_where=sa.text("status = 'ACTIVE'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_idx_active_subscription_per_user', table_name='subscriptions')
    # ### end Alembic commands ###
