"""add enums for statuses to payments and subscriptions tables

Revision ID: 3d040de1f10a
Revises: d7eb6cd64034
Create Date: 2026-08-26 05:34:30.865732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3d040de1f10a'
down_revision: Union[str, Sequence[str], None] = 'd7eb6cd64034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    subscription_status_enum = postgresql.ENUM('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscription_status_enum')
    subscription_status_enum.create(op.get_bind(), checkfirst=True)

    payment_status_enum = postgresql.ENUM('PENDING', 'SUCCEEDED', 'CANCELLED', name='payment_status_enum')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'SUCCEEDED', 'CANCELLED', name='payment_status_enum'),
               existing_nullable=False,
               postgresql_using="status::payment_status_enum")
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscription_status_enum'),
               existing_nullable=False,
               postgresql_using="status::subscription_status_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscription_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCEEDED', 'CANCELLED', name='payment_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
    subscription_status_enum = postgresql.ENUM(name='subscription_status_enum')
    subscription_status_enum.drop(op.get_bind(), checkfirst=True)

    payment_status_enum = postgresql.ENUM(name='payment_status_enum')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
