"""update the role column of the server_users table

Revision ID: 738bf9e3f49e
Revises: 27e313a91020
Create Date: 2026-08-14 09:29:14.522265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '738bf9e3f49e'
down_revision: Union[str, Sequence[str], None] = '27e313a91020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum = postgresql.ENUM("OWNER", "ADMIN", "VIEWER", name="server_user_role_enum")
    user_role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OWNER', 'ADMIN', 'VIEWER', name='server_user_role_enum'),
               existing_nullable=False,
               postgresql_using='role::server_user_role_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'VIEWER', name='server_user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
    user_role_enum = postgresql.ENUM(name="server_user_role_enum")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
