"""add login and email_confirmed columns to users table and remove unique constraint from password_hash

Revision ID: 781218c471cf
Revises: c22891d61a8f
Create Date: 2026-08-10 08:01:08.965756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781218c471cf'
down_revision: Union[str, Sequence[str], None] = 'c22891d61a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_password_hash_key'), 'users', type_='unique')
    op.create_unique_constraint("unique_login_constraint", 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_login_constraint", 'users', type_='unique')
    op.create_unique_constraint(op.f('users_password_hash_key'), 'users', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
