"""add a subscription level enum and update the subscriptions table

Revision ID: abcde31620e5
Revises: 738bf9e3f49e
Create Date: 2026-08-25 10:16:56.635530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'abcde31620e5'
down_revision: Union[str, Sequence[str], None] = '738bf9e3f49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    subscription_level_enum = postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='subscription_level_enum')
    subscription_level_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'level',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscription_level_enum'),
               existing_nullable=False,
               postgresql_using="level::subscription_level_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'level',
               existing_type=sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscription_level_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
    subscription_level_enum = postgresql.ENUM(name='subscription_level_enum')
    subscription_level_enum.drop(op.get_bind(), checkfirst=True)
